MuseumStat/imls-museum-data

.jshintrc
Gruntfile.js
app/index.html
app/scripts/config.js
app/scripts/map/cartodb-vis-directive.js
app/scripts/map/module.js
app/scripts/views/home/home-controller.js
app/scripts/views/home/home-partial.html
app/scripts/views/home/module.js
app/scripts/views/museum/module.js
app/scripts/views/museum/museum-controller.js
app/scripts/views/museum/museum-partial.html
app/styles/components/_map-tools.scss
app/styles/layout/_map.scss
bower.json
test/karma.conf.js

Proof of concept for the draw polygon/circle buttons
implemented on the home controller. Will need to add
to the museum controller as well.
TODO: It might be worth abstracting the draw trigger functions
but probably not since they'll only be used twice and are used
differently on both pages.

Add CartoDB map and slide/draw prototype

---

app/index.html
app/scripts/config.js
app/scripts/geocoder/geocoder-service.js
app/scripts/geocoder/module.js
app/scripts/views/home/home-controller.js
app/scripts/views/home/home-partial.html
app/scripts/views/home/module.js
app/styles/components/_action-bar.scss
bower.json
test/karma.conf.js

Autocompletes addresses, localities, postal, regions
Currently does nothing with the result other than
print to console

Add typeahead using ESRI geocoder

---

.gitignore
app/scripts/museum/museum-service.js
app/scripts/views/home/home-controller.js
app/scripts/views/museum/museum-partial.html

Sort by distance
Disable map scroll zoom
Default radius 1mi

Zoom map on search

---

app/scripts/acs/acs-service.js
app/scripts/acs/acs-variables.js
app/scripts/views/museum/tab-households-partial.html
app/scripts/views/museum/tab-people-partial.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/azavea/imls-museum-data/18)

calc pop weighted avg

---

app/index.html
app/scripts/acs/acs-graphs.js
app/scripts/views/museum/module.js
app/scripts/views/museum/museum-controller.js
app/scripts/views/museum/tab-households-directive.js
app/scripts/views/museum/tab-households-partial.html
app/scripts/views/museum/tab-people-directive.js
app/scripts/views/museum/tab-people-partial.html
bower.json
test/karma.conf.js

WIP, but feel free to comment
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/azavea/imls-museum-data/19)

Add pie charts

---

factual/.gitignore
factual/README.md
factual/config.yaml.template
factual/load_factual_data.py
factual/requirements.txt

Once this is merged, I'll go back and fixup the social media directive from the feature/factual branch awhile back and submit a separate PR for that.

Add factual scraper

---

app/scripts/brand/brand-directive.js

Full reload when on home page to clear list

---

app/scripts/acs/acs-variables.js
app/scripts/views/museum/tab-people-partial.html

Closes #71: Add hispanic/latino ACS variable

---

app/scripts/museum/tel-filter.js

Looks like this function was originally designed to handle strings, but the telephone number is a number in the database.

Closes #65: Correctly format telephone number

---

app/scripts/views/about/about-partial.html
app/scripts/views/footer/footer-partial.html
app/styles/pages/_secondary.scss

implemented about content from #61

about page content implemented

---

app/styles/components/_map-tools.scss

fixed map legend appearance

---

app/scripts/acs/acs-variables.js
app/scripts/views/museum/tab-people-partial.html

The variable for Hispanic/Latino population was a count, not a percentage.

Fix calculation of hispanic/latino percentage

---

app/styles/base/_print.scss
app/styles/main.scss
app/styles/pages/_museum.scss

print style sheet for museums page

---

app/styles/components/_action-bar.scss

fixed affix bar jumping on safari

---

app/index.html

Add Google Analytics tracking code

---

factual/load_factual_data.py

Make it easier to track script progress while running
Suppress urllib3 InsecurePlatformWarning
- Might want to enable this again in the future

Minor logging tweaks to load_factual_data.py

---

.gitignore
app/index.html
app/scripts/util/area-service.js
app/scripts/views/museum/museum-controller.js
app/scripts/views/museum/museum-partial.html

Always show area in sq mi
Add npm-debug.log to .gitignore
Uses area calculation functions from:
https://github.com/mapbox/geojson-area/blob/v0.2.1/index.js

Calculate and display area of analysis shape

---

app/scripts/views/museum/module.js

Fixed this one too since I've run into it a few times and its horribly unfriendly to the user

Fix bad transition to museum page when null id

---

app/scripts/views/home/search-partial.html

Tivial, merging. Fix from @jbranigan

Use gcity/gstate in search city column

---

app/scripts/views/about/about-partial.html
app/scripts/views/museum/museum-partial.html

Forgot to bump the initial year...trivial, merging.

Bump year 2009 -> 2010
